repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^testing/Baseline/
  - id: end-of-file-fixer
    exclude: ^testing/Baseline/
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v17.0.3'
  hooks:
  - id: clang-format
- repo: https://github.com/crate-ci/typos
  rev: v1.16.12
  hooks:
    - id: typos
      exclude: '^(.typos.toml|testing/.*)$'
