name: Check
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: test-${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - zeek-6.0
          - zeek-5.2
          - zeek-dev
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t ${{ matrix.image }}-quic -f docker/${{ matrix.image }}.Dockerfile .
